-- EHPS unified schema (H2 in PostgreSQL mode dialect)
-- Kept in lockstep with src/main/resources/db/postgres/schema.sql.
-- Only dialect syntax may differ between the two files; structure must match exactly.

DROP TABLE IF EXISTS machine_history;
DROP TABLE IF EXISTS repairs;
DROP TABLE IF EXISTS technician_work;
DROP TABLE IF EXISTS risk_alerts;
DROP TABLE IF EXISTS checkup_readings;
DROP TABLE IF EXISTS checkups;
DROP TABLE IF EXISTS machines;
DROP TABLE IF EXISTS machine_type_parameters;
DROP TABLE IF EXISTS machine_types;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    emp_id      BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) PRIMARY KEY,
    name        VARCHAR NOT NULL,
    email       VARCHAR NOT NULL UNIQUE,
    phone       VARCHAR,
    password    VARCHAR NOT NULL,
    role        VARCHAR NOT NULL CHECK (role IN ('manager', 'fab_coordinator', 'technician')),
    speciality  VARCHAR NULL
);

CREATE TABLE machine_types (
    type_id     BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    type_name   VARCHAR NOT NULL UNIQUE,
    code_prefix VARCHAR NOT NULL UNIQUE,
    speciality  VARCHAR NOT NULL UNIQUE,
    param_count INT NOT NULL
);

CREATE TABLE machine_type_parameters (
    param_def_id   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    type_id        BIGINT NOT NULL,
    param_index    INT NOT NULL,
    param_name     VARCHAR NOT NULL,
    unit           VARCHAR,
    good_desc      VARCHAR,
    warning_desc   VARCHAR,
    bad_desc       VARCHAR,
    CONSTRAINT fk_mtp_type FOREIGN KEY (type_id) REFERENCES machine_types (type_id),
    CONSTRAINT uq_mtp_type_param UNIQUE (type_id, param_index)
);

CREATE TABLE machines (
    machine_id   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    machine_code VARCHAR NOT NULL UNIQUE,
    type_id      BIGINT NOT NULL,
    install_date DATE,
    fab_id       BIGINT NOT NULL,
    CONSTRAINT fk_machines_type FOREIGN KEY (type_id) REFERENCES machine_types (type_id),
    CONSTRAINT fk_machines_fab FOREIGN KEY (fab_id) REFERENCES users (emp_id)
);

CREATE TABLE checkups (
    checkup_id   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    machine_id   BIGINT NOT NULL,
    tech_id      BIGINT NOT NULL,
    check_date   DATE NOT NULL,
    final_health INT NOT NULL,
    CONSTRAINT fk_checkups_machine FOREIGN KEY (machine_id) REFERENCES machines (machine_id),
    CONSTRAINT fk_checkups_tech FOREIGN KEY (tech_id) REFERENCES users (emp_id)
);

CREATE TABLE checkup_readings (
    reading_id  BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    checkup_id  BIGINT NOT NULL,
    param_index INT NOT NULL,
    reading_value REAL NOT NULL,
    status      VARCHAR NOT NULL CHECK (status IN ('good', 'warning', 'bad')),
    CONSTRAINT fk_readings_checkup FOREIGN KEY (checkup_id) REFERENCES checkups (checkup_id),
    CONSTRAINT uq_readings_checkup_param UNIQUE (checkup_id, param_index)
);

CREATE TABLE risk_alerts (
    alert_id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    machine_id        BIGINT NOT NULL,
    problem_measure    VARCHAR(500),
    severity          VARCHAR CHECK (severity IN ('high', 'medium')),
    status            VARCHAR NOT NULL CHECK (status IN ('pending', 'sent_to_manager', 'approved', 'rejected', 'resolved')),
    raised_on         DATE,
    fab_id            BIGINT,
    approved_by       BIGINT NULL,
    assigned_tech_id  BIGINT NULL,
    CONSTRAINT fk_alerts_machine FOREIGN KEY (machine_id) REFERENCES machines (machine_id),
    CONSTRAINT fk_alerts_fab FOREIGN KEY (fab_id) REFERENCES users (emp_id),
    CONSTRAINT fk_alerts_approved_by FOREIGN KEY (approved_by) REFERENCES users (emp_id),
    CONSTRAINT fk_alerts_assigned_tech FOREIGN KEY (assigned_tech_id) REFERENCES users (emp_id)
);

CREATE TABLE technician_work (
    work_id     BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    machine_id  BIGINT NOT NULL,
    tech_id     BIGINT NOT NULL,
    fab_id      BIGINT,
    work_type   VARCHAR NOT NULL CHECK (work_type IN ('checkup', 'repair')),
    work_date   DATE,
    completed   BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_work_machine FOREIGN KEY (machine_id) REFERENCES machines (machine_id),
    CONSTRAINT fk_work_tech FOREIGN KEY (tech_id) REFERENCES users (emp_id),
    CONSTRAINT fk_work_fab FOREIGN KEY (fab_id) REFERENCES users (emp_id)
);

CREATE TABLE repairs (
    repair_id      BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    machine_id     BIGINT NOT NULL,
    tech_id        BIGINT NOT NULL,
    alert_id       BIGINT,
    repair_date    DATE,
    changes_done   VARCHAR(1000),
    observations   VARCHAR(1000),
    CONSTRAINT fk_repairs_machine FOREIGN KEY (machine_id) REFERENCES machines (machine_id),
    CONSTRAINT fk_repairs_tech FOREIGN KEY (tech_id) REFERENCES users (emp_id),
    CONSTRAINT fk_repairs_alert FOREIGN KEY (alert_id) REFERENCES risk_alerts (alert_id)
);

CREATE TABLE machine_history (
    history_id     BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    machine_id     BIGINT NOT NULL,
    tech_id        BIGINT NOT NULL,
    alert_id       BIGINT,
    history_date   DATE,
    issue          VARCHAR(1000),
    repair_action  VARCHAR(1000),
    observations   VARCHAR(1000),
    CONSTRAINT fk_history_machine FOREIGN KEY (machine_id) REFERENCES machines (machine_id),
    CONSTRAINT fk_history_tech FOREIGN KEY (tech_id) REFERENCES users (emp_id),
    CONSTRAINT fk_history_alert FOREIGN KEY (alert_id) REFERENCES risk_alerts (alert_id)
);
